import type { PendingRosterSelectionWarning } from "@/services/roster-selection-risk";
export const DOMAIN_ERROR_CODES = [
  "NOT_AUTHENTICATED",
  "NOT_AUTHORIZED",
  "ACCOUNT_DISABLED",
  "VALIDATION_FAILED",
  "CHARACTER_NOT_ELIGIBLE",
  "SIGNUP_CLOSED",
  "INVALID_STATE_TRANSITION",
  "NOT_FOUND",
  "DUPLICATE_SIGNUP",
  "CHARACTER_NOT_FOUND",
  "CHARACTER_NOT_OWNED",
  "CHARACTER_INACTIVE",
  "CHARACTER_HAS_OPEN_SIGNUPS",
  "CHARACTER_ALREADY_SELECTED_OTHER_RUN",
  "CHARACTER_UNAVAILABLE",
  "CHARACTER_SCHEDULE_CONFLICT",
  "ROSTER_HAS_SCHEDULE_CONFLICTS",
  "CHARACTER_ALREADY_EXISTS",
  "AVAILABILITY_BLOCK_NOT_FOUND",
  "INVALID_CHARACTER_NAME",
  "INVALID_REALM",
  "INVALID_SPECIALIZATION",
  "INVALID_CLASS_SPECIALIZATION",
  "INVALID_PLAYABLE_SPEC",
  "INVALID_ITEM_LEVEL",
  "INVALID_CHARACTER_ROLE",
  "CHARACTER_CLASS_IMMUTABLE",
  "BOOSTER_ACCESS_REQUIRED",
  "RUN_NOT_MANAGEABLE",
  "SIGNUP_WITHDRAWN",
  "SIGNUP_OFFER_DUPLICATE_CHARACTER",
  "SIGNUP_OFFER_ROSTER_SELECTED",
  "WITHDRAW_REASON_REQUIRED",
  "INVALID_ROSTER_SELECTION",
  "ROSTER_VALIDATION_FAILED",
  "ROSTER_ALREADY_CHANGED",
  "ROSTER_WARNING_CONFIRMATION_REQUIRED",
  "BOOSTER_ACCESS_INVALID",
  "BOOSTER_ACCESS_NOT_FOUND",
  "BOOSTER_ACCESS_ALREADY_PENDING",
  "BOOSTER_ACCESS_ALREADY_APPROVED",
  "BOOSTER_ACCESS_INVALID_TRANSITION",
  "BOOSTER_ACCESS_ROLE_INVALID",
  "RUN_INVALID_TRANSITION",
  "RUN_ALREADY_OPEN",
  "RUN_SIGNUPS_ALREADY_OPEN",
  "RUN_SIGNUPS_ALREADY_CLOSED",
  "RUN_IDENTITY_LOCKED",
  "RUN_EDIT_LOCKED",
  "RUN_CANNOT_CANCEL",
  "RUN_CANNOT_REACTIVATE",
  "RUN_RAID_LEAD_INVALID",
  "RUN_SCHEDULE_INVALID",
  "RUN_LOOT_TYPE_INVALID",
  "RUN_BOSS_COUNT_INVALID",
  "RAID_NOT_AVAILABLE_FOR_RUNS",
  "RUN_PRODUCT_UNAVAILABLE",
  "RUN_PRODUCT_SELECTION_INVALID",
  "RUN_CANNOT_START",
  "ROSTER_UNPUBLISHED_CHANGES",
  "RUN_NOT_PUBLISHED",
  "RUN_ALREADY_STARTED",
  "RUN_CANNOT_COMPLETE",
  "RUN_ALREADY_ARCHIVED",
  "RUN_CANNOT_ARCHIVE",
  "RUN_NOT_ARCHIVED",
  "RUN_CANNOT_DELETE",
  "ATTENDANCE_NOT_FOUND",
  "ATTENDANCE_NOT_MANAGEABLE",
  "ATTENDANCE_INVALID_STATUS",
  "ATTENDANCE_INCOMPLETE",
  "PAYOUT_RUN_NOT_COMPLETED",
  "PAYOUT_ALREADY_EXISTS",
  "PAYOUT_NOT_FOUND",
  "PAYOUT_NOT_MANAGEABLE",
  "PAYOUT_NOT_DRAFT",
  "PAYOUT_INVALID_TOTAL",
  "PAYOUT_NO_ELIGIBLE_SHARES",
  "PAYOUT_INVALID_SHARE",
  "PAYOUT_INVALID_CUT_MODE",
  "PAYOUT_FINALIZED",
  "PAYOUT_ALREADY_PAID",
  "PAYOUT_ADMIN_REQUIRED",
  "PAYOUT_ATTENDANCE_INVALID",
  "BATTLENET_NOT_CONFIGURED",
  "BATTLENET_NOT_CONNECTED",
  "BATTLENET_STATE_INVALID",
  "BATTLENET_AUTH_FAILED",
  "BATTLENET_ACCOUNT_PROFILE_FORBIDDEN",
  "BATTLENET_IMPORT_SESSION_NOT_FOUND",
  "BATTLENET_IMPORT_SESSION_EXPIRED",
  "BATTLENET_API_UNAVAILABLE",
  "BATTLENET_RATE_LIMITED",
  "BLIZZARD_CHARACTER_NOT_FOUND",
  "BLIZZARD_CHARACTER_NOT_OWNED",
  "BLIZZARD_REGION_MISMATCH",
  "BLIZZARD_IDENTITY_CONFLICT",
  "BLIZZARD_PROFILE_UNAVAILABLE",
  "BLIZZARD_SYNC_FAILED",
  "BLIZZARD_REFRESH_COOLDOWN",
  "CHARACTER_SYNC_IN_PROGRESS",
  "CHARACTER_SYNC_NOT_ELIGIBLE",
  "CHARACTER_SYNC_ALREADY_RUNNING",
  "CHARACTER_BULK_REFRESH_COOLDOWN",
  "BLIZZARD_LEVEL_TOO_LOW",
  "USER_MANAGEMENT_FORBIDDEN",
  // Content Catalog (/manage/content)
  "CONTENT_RAID_NOT_FOUND",
  "CONTENT_RAID_IN_USE",
  "CONTENT_ENCOUNTER_NOT_FOUND",
  "CONTENT_ENCOUNTER_IN_USE",
  "CONTENT_BLIZZARD_INSTANCE_CONFLICT",
  "CONTENT_BLIZZARD_ENCOUNTER_CONFLICT",
  "CONTENT_WCL_ENCOUNTER_CONFLICT",
  "CONTENT_PRODUCT_NOT_FOUND",
  "CONTENT_PRODUCT_KEY_CONFLICT",
  "CONTENT_PRODUCT_EMPTY",
  "CONTENT_PRODUCT_IN_USE",
  "CONTENT_DUPLICATE_PRODUCT_RAID",
  "CONTENT_INVALID_BOSS_COUNT",
  "USER_NOT_FOUND",
  "INVALID_ACCOUNT_ROLE",
  "ROLE_ALREADY_ASSIGNED",
  "LAST_ADMIN_REQUIRED",
  "OWNER_ROLE_PROTECTED",
  "OWNER_ASSIGNMENT_REQUIRES_BOOTSTRAP",
  "OWNER_ALREADY_EXISTS",
  "OWNER_BOOTSTRAP_TARGET_INVALID",
  "ROLE_CHANGE_BLOCKED_BY_ACTIVE_RUNS",
  "BOOSTER_ACCESS_SELF_REQUEST_DISABLED",
  "STRIKE_NOT_FOUND",
  "STRIKE_NOT_MANAGEABLE",
  "STRIKE_RUN_REQUIRED",
  "STRIKE_USER_NOT_ASSOCIATED",
  "STRIKE_ALREADY_REVOKED",
  "STRIKE_REVOKE_FORBIDDEN",
  "RUN_TEMPLATE_NOT_FOUND",
  "RUN_TEMPLATE_ALREADY_ACTIVE",
  "RUN_TEMPLATE_ALREADY_INACTIVE",
  "RUN_TEMPLATE_UNUSABLE",
  "RUN_TEMPLATE_RAID_LEAD_MISMATCH",
  "CONSUMABLE_AUDIT_RUN_NOT_COMPLETED",
  "CONSUMABLE_AUDIT_REPORT_REQUIRED",
  "CONSUMABLE_AUDIT_REFRESH_COOLDOWN",
  "COMMUNITY_SCHEDULE_NOT_FOUND",
  "COMMUNITY_SCHEDULE_DUPLICATE",
  "COMMUNITY_SCHEDULE_BATCH_DUPLICATE",
  "COMMUNITY_SCHEDULE_SLOTS_EMPTY",
  "COMMUNITY_SCHEDULE_SLOTS_TOO_MANY",
  "COMMUNITY_SCHEDULE_ALREADY_ACTIVE",
  "COMMUNITY_SCHEDULE_ALREADY_INACTIVE",
  "COMMUNITY_SCHEDULE_RAID_LEAD_INVALID",
  "COMMUNITY_SCHEDULE_INVALID_WEEKDAY",
  "COMMUNITY_SCHEDULE_INVALID_TIME",
  "SCHEDULE_OCCURRENCE_ALREADY_CREATED",
  "COMMUNITY_SCHEDULE_TEMPLATE_REQUIRED",
  "COMMUNITY_SCHEDULE_TEMPLATE_LEAD_MISMATCH",
  "COMMUNITY_SCHEDULE_TEMPLATE_INVALID",
  "COMMUNITY_SCHEDULE_OCCURRENCE_PAST",
  "COMMUNITY_SCHEDULE_SLOT_INACTIVE",
] as const;

export type DomainErrorCode = (typeof DOMAIN_ERROR_CODES)[number];

/**
 * Expected business failure. Controllers map these to user-facing messages
 * instead of leaking database or infrastructure errors.
 */
export class DomainError extends Error {
  readonly code: DomainErrorCode;
  readonly status: number;

  /**
   * `options.cause` keeps an underlying (domain) error attached when a caller
   * folds it into a broader user-facing error — e.g. so sync telemetry can
   * still classify the original Blizzard failure. Never shown to users.
   */
  constructor(code: DomainErrorCode, message: string, status = 400, options?: { cause?: unknown }) {
    super(message, options);
    this.name = "DomainError";
    this.code = code;
    this.status = status;
  }
}

/**
 * A NEW roster selection carries a warning (e.g. lockout progress) the Raid
 * Lead has not acknowledged for its current state. Carries the current
 * warnings so the UI can (re-)prompt; nothing was written. Never used for
 * hard conflicts — those stay plain DomainErrors and cannot be acknowledged.
 */
export class RosterWarningConfirmationRequiredError extends DomainError {
  readonly pendingWarnings: PendingRosterSelectionWarning[];

  constructor(message: string, pendingWarnings: PendingRosterSelectionWarning[]) {
    super("ROSTER_WARNING_CONFIRMATION_REQUIRED", message);
    this.name = "RosterWarningConfirmationRequiredError";
    this.pendingWarnings = pendingWarnings;
  }
}

export function isDomainError(error: unknown): error is DomainError {
  return error instanceof DomainError;
}
